before_script:
  - npm install;
  
language: node_js
os:
  - windows
  - linux

node_js:
  - "11"
  - "10"
  - "8"
  - "6"

notifications:
  email:
    on_success: never
    on_failure: always

env:
  - PORT=7777
