language: node_js
os:
  - windows
  - linux

node_js:
  - "11"
  - "10"
  - "8"
  - "6"


script:
  - npm run lint && npm run coveralls -- -c && npm run typescript
  - npm run license-checker

notifications:
  email:
    on_success: never
    on_failure: always

env:
  - PORT=7777
